Anyx\CrosswordBundle\Document\ObjectWithVirtualProperties:
    properties:
        existField:
            type: string
    virtual_properties:
        getVirtualValue: ~
        getVirtualSerializedValue:
            serialized_name: tests