<?php

namespace Anyx\CrosswordBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Anyx\CrosswordBundle\Document;

/**
 * CrosswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolutionRepository extends DocumentRepository {

	/**
	 * @param \Anyx\CrosswordBundle\Document\User $user
	 * @param \Anyx\CrosswordBundle\Document\Crossword $crossword
	 * @return Document\Solution
	 */
	public function getUserSolution( Document\User $user, Document\Crossword $crossword ) {
		return $this->findOneBy(
					array(
						'crossword.id'	=> $crossword->getId(),
						'user.id' 		=> $user->getId()
					)
		);
	}
}