imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        pagerfanta_opts:
            previous_message: '&laquo;'
            next_message:     '&raquo;'
            dots_message:     '...'
    form:
        resources:
            - 'AnyxCrosswordBundle:Form:fields.html.twig'

jms_serializer:
    handlers:
        datetime:
            default_format: "d.m.Y" 

doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
   
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
#    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: crosswords_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true

fos_user:
    db_driver: mongodb
    service:
        user_manager: anyx_social_user.user.manager
    firewall_name: main
    user_class: Anyx\CrosswordBundle\Document\User
    profile:
      form:
        type: anyx_user_profile

anyx_social_user:
  db_driver: mongodb
  accounts:
    class: Anyx\SocialUserBundle\Document\SocialAccount
    map:
      facebook:
        accountId: id
        userName: name
        avatar: picture.data.url
        link: link
      twitter:
        accountId: id
        userName: name
        avatar: profile_image_url
        link: screen_name
      vkontakte:
        accountId: response.0.uid
        userName: response.0.first_name + response.0.last_name
        avatar: response.0.photo
        link: response.0.screen_name

anyx_social:
  services:
    facebook:
      client_id:         %facebook_client_id%
      secret:            %facebook_secret%
      user_fields:       picture,email,name,link
      scope:             email
    twitter:
      client_id:         %twitter_client_id%
      secret:            %twitter_secret%
      scope:             email,user_about_me
    vkontakte:
      client_id:         %vkontakte_client_id%
      secret:            %vkontakte_secret%
      scope:             notify,offline
      user_fields:       uid, first_name, last_name, nickname, screen_name, sex, bdate (birthdate), city, country, timezone, photo, photo_medium, photo_big, has_mobile, rate, contacts, education, online, counters

foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            ru_snowball:
                                type : snowball
                                language: Russian
            types:
                crossword:
                    mappings:
                        title: 
                            boost: 10,
                            analyzer: ru_snowball
                        description: 
                            boost: 7,
                            analyzer: ru_snowball
                        words_definitions_as_string:
                            boost: 5,
                            analyzer: ru_snowball
                        tags_texts:
                            boost: 7
                        publishedAt:
                           boost: 5
                        rating:
                           boost: 5
                        countSolvings:
                           type: integer

                          
                    persistence:
                        driver: mongodb
                        model: Anyx\CrosswordBundle\Document\Crossword
                        listener:
                            is_indexable_callback: "isAccessible"
                        finder:
                        provider:
                            batch_size: 100
                            query_builder_method: getPublicCrosswordsQueryBuilder

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text: 
        sonata.block.service.action:
        sonata.block.service.rss:

sonata_admin:
    title:     Editor
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            sonata_page:
                label: Documents
                items: 
                  - sonata.admin.page
                  - sonata.admin.user
#aliases
services:
    anyx.dm: "@doctrine.odm.mongodb.document_manager"

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags: [{ name: 'twig.extension' }]
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags: [{ name: 'twig.extension' }]
        
    user.listener:
      class: Anyx\CrosswordBundle\Listener\UserListener
      tags:
        - { name: kernel.event_listener, event: anyx_social_users.merge, method: onMergeUsers}
        - { name: kernel.event_listener, event: anyx_social_users.create, method: onCreateUser}
    solution.listener:
      class: Anyx\CrosswordBundle\Listener\SolutionListener
      tags:
        - { name: doctrine_mongodb.odm.event_listener, event: postPersist, method: postPersist}
    tags.subscriber:
      class: Anyx\CrosswordBundle\Listener\TagsSubscriber
      tags:
        - { name: doctrine_mongodb.odm.event_subscriber}
    estimates.subscriber:
      class: Anyx\CrosswordBundle\Listener\CrosswordEstimateSubscriber
      tags:
        - { name: doctrine_mongodb.odm.event_subscriber}
        
    form.type.tags:
      class: Anyx\CrosswordBundle\Form\Extension\Type\TagsType
      tags:
        -  { name: form.type, alias: tags }