AnyxSocialUserBundle:
    resource: "@AnyxSocialUserBundle/Controller/"
    type:     annotation
    prefix:   /

AnyxSocialBundle:
    resource: "@AnyxSocialBundle/Controller/"
    type:     annotation
    prefix:   /

AnyxUserBundle:
    resource: "@AnyxUserBundle/Controller/"
    type:     annotation

#anyx_social_bundle:
#    resource: anyx_social.controller.login
#    type:     annotation
  
crosswords:
    resource: "@AnyxCrosswordBundle/Resources/config/routing/common.yml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
fos_user:
    resource: "@AnyxCrosswordBundle/Resources/config/routing/fos_user.yml"
#crosswords_rest:
#    type:     rest
#    resource: Anyx\CrosswordBundle\Controller\CrosswordRestController