AnyxPageBundle:
    resource: "@AnyxPageBundle/Controller/"
    type:     annotation
    prefix:   /

AnyxSocialUserBundle:
    resource: "@AnyxSocialUserBundle/Controller/"
    type:     annotation
    prefix:   /

AnyxUserBundle:
    resource: "@AnyxUserBundle/Controller/"
    type:     annotation

crosswords:
    resource: "@AnyxCrosswordBundle/Resources/config/routing/common.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
fos_user:
    resource: "@AnyxCrosswordBundle/Resources/config/routing/fos_user.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user_impersonating:
    pattern: /
    defaults: { _controller: SonataPageBundle:Page:catchAll }

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin