parameters:
    anyx.document.factory.class: Anyx\CrosswordBundle\Document\Factory
    anyx.document.aliases:
        Crossword: Anyx\CrosswordBundle\Document\Crossword
        Word: Anyx\CrosswordBundle\Document\Word
        
    doctrine.mapping.abstract.type.class: \Doctrine\ODM\MongoDB\Mapping\Types\Type
    doctrine.mapping.confugurator.class:  Anyx\CrosswordBundle\Doctrine\Mapping\Configurator
    anyx.mapping.types:
          Point: Anyx\CrosswordBundle\Doctrine\Type\Point
    
services:
    anyx.document.factory:
        class: %anyx.document.factory.class%
        arguments: [ "@doctrine.odm.mongodb.document_manager", %anyx.document.aliases%]
#    anyx.doctrine.mapping.listener:
#        class:  %doctrine.mapping.confugurator.class%
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: registerAdditionalTypes }