default:
    resource: "@AnyxCrosswordBundle/Controller/DefaultController.php"
    type:     annotation

crossword:
    resource: "@AnyxCrosswordBundle/Controller/CrosswordController.php"
    type:     annotation
    
constructor:
    resource: "@AnyxCrosswordBundle/Controller/ConstructorController.php"
    type:     annotation

solving: 
    resource: "@AnyxCrosswordBundle/Controller/SolvingController.php"
    type:     annotation

#words_save:
#    pattern:  /constructor/{id}/save
#    defaults: { _controller: AnyxCrosswordBundle:Constructor:save }

crossword_new:
    pattern:  /crossword/new
    defaults: { _controller: AnyxCrosswordBundle:Crossword:new }    

crossword_edit:
    pattern:  /crossword/edit/{id}
    defaults: { _controller: AnyxCrosswordBundle:Crossword:edit }    
