default:
    resource: "@AnyxCrosswordBundle/Controller/DefaultController.php"
    type:     annotation

crossword:
    resource: "@AnyxCrosswordBundle/Controller/CrosswordController.php"
    type:     annotation
    
constructor:
    resource: "@AnyxCrosswordBundle/Controller/ConstructorController.php"
    type:     annotation

solving: 
    resource: "@AnyxCrosswordBundle/Controller/SolvingController.php"
    type:     annotation

lists:
    resource: "@AnyxCrosswordBundle/Controller/ListsController.php"
    type:     annotation

#todo  
report:
    pattern:  /report
    defaults: { _controller: AnyxPageBundle:Page:index, slug : 'report' }

crossword_edit:
    pattern:  /crossword/edit/{id}
    defaults: { _controller: AnyxCrosswordBundle:Crossword:edit }    
